### ISSUE TITLE
TRANSPORTPI AES running on Volumio+Tidal problem

### ISSUE THREAD

**Issue by Joonyahny** [iancanada/DocumentDownload#10]
Hi 
I have TRANSPORTPI AES running on Volumio+Tidal and having problems with 24bit 192 music streaming. Music is stuttering. I mean it is like stop and go and stop and go situation.  It happens only on 24bit 192 music.  Clock signal is provided by FifoPiQ7.  I have accusilicon clock chips and they showed problems so I changed back to the original parts and the problem persists.  can you help me on this?

**Comment by iancanada** [comment]
Can you send me a picture of your system?

**Comment by Joonyahny** [comment]
![20240106_150046](https://github.com/iancanada/DocumentDownload/assets/155713177/73e98019-f1e0-4282-bd04-cb6b8674bd9a)
![20240106_150022](https://github.com/iancanada/DocumentDownload/assets/155713177/6831bd4c-cb53-4f33-8152-9a90c9066fa7)
![20240106_150010](https://github.com/iancanada/DocumentDownload/assets/155713177/c34fdbb9-8af1-4fba-9c82-e883d3c14f09)
![Uploading 20240106_150001.jpg…]()

**Comment by iancanada** [comment]
What's your DAC? Did you have this issue before?

**Comment by Joonyahny** [comment]
I am using Brooklyn DAC+. Never had this kind of problem before.  I also have TRANSPORTPI DIGI and I do not have a same problem.

**Comment by Joonyahny** [comment]
TransportPI and DAC is connected with 75ohm digital COAX cable.

**Comment by iancanada** [comment]
Do you mean the system has been working and has a problem suddenly?
Can you re-connect the MCLK cable? Can you try other DAC to exclude the DAC
issue?

Thanks
Ian

**Comment by Joonyahny** [comment]
No. The system is working fine with TransportPI DIGI (I mean any frequency) but it is not working with AES.  I have two units, DIGI and AES+Q7.  AES shows interruptions (stuttering) during streaming of 24bit 192 khz.  Lower than this, it is working fine.  I assume the limit for my AES unit is 24bit 192 khz.  Tried re-connection but problem remains and unfortunately, Brooklyn DAC+ is the only DAC I have.

**Comment by iancanada** [comment]
I'm trying to duplicate your case with the same configuration today. But I
don't have any problem playing 192KHz 24bit music with three of my DACs.
All OPT.RCA and AES cables are good.
I really want to address your issue. If you want, you can send both Q7 and
AES back to me to check.

BTW, Q7+AES needs the Audiophoincs ESS DAC as the Linux driver. I think you
have already chosen it correctly.

Please let me know.

Regards
Ian

**Comment by Joonyahny** [comment]
Thanks Ian.  Yes I have chosen the Audiophonics driver.  I will send you Q7+AES for check.  Can you send me the address?

**Comment by iancanada** [comment]
Please list it as "hobby PCB to repair $10-" on the shipping paperwork to
avoid any additional cost.Please don't forget to put a printed note about
your case and your email, as well as your address.Please let me know if you
have a tracking number.
IanCanada
71 Meadowbank Rd,Etobicoke,
ON M9B 5C7,
Canada
6472273388

**Comment by Joonyahny** [comment]
Thanks Ian. Will get back to you soon.

**Comment by Joonyahny** [comment]
Hi Ian, just one question.  Can AES play 32 bit 44.1khz?  I just directly connected my dac to the computer and some of the songs that could not played with AES were not 24 bit 192, those were 32 bit 44.1khz.  So maybe I was streaming higher spec file than AES can handle?

**Comment by iancanada** [comment]
Try to play true 192KHz/24bit to see if it is OK. If you have a
MonitorPi/Pro, you can see the real format.

Regards,
Ian

**Comment by Joonyahny** [comment]
OK. I do not have monitorPI but will try 24/192.  And can AES play 32/44.1?  what would be the limit?

**Comment by iancanada** [comment]
44.1K/32bit looks very special. The software may play it in a special
physical format. But you don't have a MonitorPi or Por so you can not see.
